	-- Updated Database Schema with Consistent Role ID References

	CREATE SCHEMA IF NOT EXISTS planificacion_inventario;

	USE planificacion_inventario;

	-- tables
	-- Table: ALMACEN
	CREATE TABLE ALMACEN (
		ID bigint NOT NULL AUTO_INCREMENT,
		UBICACION varchar(500) NOT NULL,
		FECHA_ACTUALIZACION date NOT NULL,
		ENCARGADO_ALMACEN_ID bigint NOT NULL,
		CONSTRAINT ALMACEN_pk PRIMARY KEY (ID)
	);

	-- Table: ASIGNACION_HERRAMIENTA
	CREATE TABLE ASIGNACION_HERRAMIENTA (
		ID int NOT NULL AUTO_INCREMENT,
		CANTIDAD int NOT NULL,
		FLUJO_HERRAMIENTA_ID int NOT NULL,
		PROYECTO_ID bigint NOT NULL,
		FASE varchar(50) NOT NULL,
		CONSTRAINT ASIGNACION_HERRAMIENTA_pk PRIMARY KEY (ID)
	);

	-- Table: ASIGNACION_MATERIAL
	CREATE TABLE ASIGNACION_MATERIAL (
		ID int NOT NULL AUTO_INCREMENT,
		FLUJO_MATERIAL_ID int NOT NULL,
		PROYECTO_ID bigint NOT NULL,
		CANTIDAD int NOT NULL,
		FASE varchar(50) NOT NULL,
		CONSTRAINT ASIGNACION_MATERIAL_pk PRIMARY KEY (ID)
	);

	-- Table: COMPRA_HERRAMIENTA
	CREATE TABLE COMPRA_HERRAMIENTA (
		ID int NOT NULL AUTO_INCREMENT,
		COSTO_TOTAL decimal(11,2) NOT NULL,
		PROVEEDOR_ID bigint NOT NULL,
		FECHA datetime NOT NULL,
		DETALLE varchar(200) NOT NULL,
		CONSTRAINT COMPRA_HERRAMIENTA_pk PRIMARY KEY (ID)
	);

	-- Table: COMPRA_MATERIAL
	CREATE TABLE COMPRA_MATERIAL (
		ID int NOT NULL AUTO_INCREMENT,
		COSTO_TOTAL decimal(11,2) NOT NULL,
		FECHA datetime NOT NULL,
		PROVEEDOR_ID bigint NOT NULL,
		DETALLE varchar(200) NOT NULL,
		CONSTRAINT COMPRA_MATERIAL_pk PRIMARY KEY (ID)
	);

	-- Table: DETALLE_COMPRA_HERRAMIENTA
	CREATE TABLE DETALLE_COMPRA_HERRAMIENTA (
		ID int NOT NULL AUTO_INCREMENT,
		COSTO decimal(7,2) NOT NULL,
		HERRAMIENTA_ID bigint NOT NULL,
		COMPRA_HERRAMIENTA_ID int NOT NULL,
		CANTIDAD int NOT NULL,
		CONSTRAINT DETALLE_COMPRA_HERRAMIENTA_pk PRIMARY KEY (ID)
	);

	-- Table: DETALLE_COMPRA_MATERIAL
	CREATE TABLE DETALLE_COMPRA_MATERIAL (
		ID int NOT NULL AUTO_INCREMENT,
		COSTO decimal(7,2) NOT NULL,
		CANTIDAD int NOT NULL,
		MATERIAL_ID int NOT NULL,
		COMPRA_MATERIAL_ID int NOT NULL,
		CONSTRAINT DETALLE_COMPRA_MATERIAL_pk PRIMARY KEY (ID)
	);

	-- Table: EMPLEADO
	CREATE TABLE EMPLEADO (
		ID bigint NOT NULL AUTO_INCREMENT,
		NOMBRE char(255) NOT NULL,
		ROL char(255) NOT NULL,
		TELFONO char(255) NOT NULL,
		FECHA_REGISTRO int NOT NULL,
		CONSTRAINT EMPLEADO_pk PRIMARY KEY (ID)
	);

	-- Table: EMPLEADO_EQUIPO
	CREATE TABLE EMPLEADO_EQUIPO (
		ID bigint NOT NULL AUTO_INCREMENT,
		EQUIPO_ID bigint NOT NULL,
		USUARIO_ID bigint NOT NULL,
		CONSTRAINT EMPLEADO_EQUIPO_pk PRIMARY KEY (ID)
	);

	-- Table: ENCARGADO_ALMACEN
	CREATE TABLE ENCARGADO_ALMACEN (
		ID bigint NOT NULL AUTO_INCREMENT,
		NIVEL_ACCESO char(255) NOT NULL,
		NOTIFICACIONES_ACTIVAS boolean NOT NULL,
		USUARIO_ID bigint NOT NULL,
		CONSTRAINT ENCARGADO_ALMACEN_pk PRIMARY KEY (ID)
	);

	-- Table: ENCARGADO_FINANZAS
	CREATE TABLE ENCARGADO_FINANZAS (
		ID bigint NOT NULL AUTO_INCREMENT,
		USUARIO_ID bigint NOT NULL,
		CONSTRAINT ENCARGADO_FINANZAS_pk PRIMARY KEY (ID)
	);

	-- Table: ENCARGADO_PROYECTO
	CREATE TABLE ENCARGADO_PROYECTO (
		ID bigint NOT NULL AUTO_INCREMENT,
		USUARIO_ID bigint NOT NULL,
		CONSTRAINT ENCARGADO_PROYECTO_pk PRIMARY KEY (ID)
	);

	-- Table: EQUIPO
	CREATE TABLE EQUIPO (
		ID bigint NOT NULL AUTO_INCREMENT,
		NOMRE char(255) NOT NULL,
		FECHA_CREACION datetime NOT NULL,
		ESTADO char(255) NOT NULL,
		UBICACION varchar(500) NOT NULL,
		PROYECTO_ID bigint NOT NULL,
		CONSTRAINT EQUIPO_pk PRIMARY KEY (ID)
	);

	-- Table: FLUJO_HERRAMIENTA
	CREATE TABLE FLUJO_HERRAMIENTA (
		ID int NOT NULL AUTO_INCREMENT,
		CANTIDAD int NOT NULL,
		MOVIMIENTO enum('entrada','salida') NOT NULL,
		FECHA datetime NOT NULL,
		ALMACEN_ID bigint NOT NULL,
		HERRAMIENTA_ID bigint NOT NULL,
		CONSTRAINT FLUJO_HERRAMIENTA_pk PRIMARY KEY (ID)
	);

	-- Table: FLUJO_MATERIAL
	CREATE TABLE FLUJO_MATERIAL (
		ID int NOT NULL AUTO_INCREMENT,
		MATERIAL_ID int NOT NULL,
		ALMACEN_ID bigint NOT NULL,
		CANTIDAD int NOT NULL,
		MOVIMIENTO enum('entrada','salida') NOT NULL,
		FECHA datetime NOT NULL,
		CONSTRAINT FLUJO_MATERIAL_pk PRIMARY KEY (ID)
	);

	-- Table: GERENTE_INVENTARIO
	CREATE TABLE GERENTE_INVENTARIO (
		ID bigint NOT NULL AUTO_INCREMENT,
		NIVEL_ACCESO char(255) NOT NULL,
		ENCARGADO_PEDIDOS boolean NOT NULL,
		NOTIFICACIONES_ACTIVAS boolean NOT NULL,
		USUARIO_ID bigint NOT NULL,
		CONSTRAINT GERENTE_INVENTARIO_pk PRIMARY KEY (ID)
	);

	-- Table: HERRAMIENTA
	CREATE TABLE HERRAMIENTA (
		ID bigint NOT NULL AUTO_INCREMENT,
		NOMBRE char(255) NOT NULL,
		DESCRIPCION varchar(500) NOT NULL,
		CANTIDAD int NOT NULL,
		PRECIO_UNITARIO int NOT NULL,
		CANTIDAD_MINIMA int NOT NULL,
		CONSTRAINT HERRAMIENTA_pk PRIMARY KEY (ID)
	);

	-- Table: H_HERRAMIENTA
	CREATE TABLE H_HERRAMIENTA (
		ID bigint NOT NULL AUTO_INCREMENT,
		NOMBRE char(255) NOT NULL,
		DESCRIPCION varchar(500) NOT NULL,
		CANTIDAD int NOT NULL,
		PRECIO_UNITARIO int NOT NULL,
		PROVEEDOR_ID bigint NOT NULL,
		CANTIDAD_MINIMA int NOT NULL,
		CONSTRAINT HERRAMIENTA_pk PRIMARY KEY (ID)
	);

	-- Table: H_MATERIAL
	CREATE TABLE H_MATERIAL (
		ID int NOT NULL AUTO_INCREMENT,
		NOMBRE char(255) NOT NULL,
		DESCRIPCION varchar(500) NOT NULL,
		CANTIDAD int NOT NULL,
		PRECIO_UNITARIO int NOT NULL,
		PROVEEDOR_ID bigint NOT NULL,
		CANTIDAD_MINIMA int NOT NULL,
		CONSTRAINT MATERIAL_pk PRIMARY KEY (ID)
	);

	-- Table: MATERIAL
	CREATE TABLE MATERIAL (
		ID int NOT NULL AUTO_INCREMENT,
		NOMBRE char(255) NOT NULL,
		DESCRIPCION varchar(500) NOT NULL,
		CANTIDAD int NOT NULL,
		PRECIO_UNITARIO int NOT NULL,
		CANTIDAD_MINIMA int NOT NULL,
		CONSTRAINT MATERIAL_pk PRIMARY KEY (ID)
	);

	-- Table: PROVEEDOR
	CREATE TABLE PROVEEDOR (
		ID bigint NOT NULL AUTO_INCREMENT,
		NOMBRE char(255) NOT NULL,
		DIRECCION char(255) NOT NULL,
		TELEFONO char(255) NOT NULL,
		CONSTRAINT PROVEEDOR_pk PRIMARY KEY (ID)
	);

	-- Table: PROYECTO
	CREATE TABLE PROYECTO (
		ID bigint NOT NULL AUTO_INCREMENT,
		NOMBRE char(255) NOT NULL,
		DESCRIPCION varchar(500) NOT NULL,
		CRONOGRAMA varchar(500) NOT NULL,
		PRESUPUESTO_ASIGNADO decimal(15,2) NOT NULL,
		METAS_FINANCIERAS decimal(15,2) NOT NULL,
		ESTADO char(255) NOT NULL,
		PRIORIDAD char(255) NOT NULL,
		FECHA_INICIO date NOT NULL,
		FECHA_FIN date NOT NULL,
		ENCARGADO_PROYECTO_ID bigint NOT NULL,
		GERENTE_INVENTARIO_ID bigint NOT NULL,
		ENCARGADO_FINANZAS_ID bigint NOT NULL,
		CONSTRAINT PROYECTO_pk PRIMARY KEY (ID)
	);

	-- Table: REPORTE
	CREATE TABLE REPORTE (
		ID bigint NOT NULL AUTO_INCREMENT,
		FECHA_CREACION datetime NOT NULL,
		DETALLE varchar(1000) NOT NULL,
		ENCARGADO_FINANZAS_ID bigint NOT NULL,
		ENCARGADO_ALMACEN_ID bigint NOT NULL,
		CONSTRAINT REPORTE_pk PRIMARY KEY (ID)
	);

	-- Table: SOBRANTE_PROYECTO
	CREATE TABLE SOBRANTE_PROYECTO (
		ID int NOT NULL AUTO_INCREMENT,
		CANTIDAD int NOT NULL,
		ASIGNACION_MATERIAL_ID int NOT NULL,
		CONSTRAINT SOBRANTE_PROYECTO_pk PRIMARY KEY (ID)
	);

	-- Table: USO_MATERIAL
	CREATE TABLE USO_MATERIAL (
		ID int NOT NULL AUTO_INCREMENT,
		ASIGNACION_MATERIAL_ID int NOT NULL,
		CANTIDAD int NOT NULL,
		FECHA date NOT NULL,
		DETALLE text NOT NULL,
		CONSTRAINT USO_MATERIAL_pk PRIMARY KEY (ID)
	);

	-- Table: USUARIO
	CREATE TABLE USUARIO (
		ID bigint NOT NULL AUTO_INCREMENT,
		PASSWOR_HASH varchar(500) NOT NULL,
		USER_NAME varchar(500) NOT NULL,
		EMAIL varchar(500) NOT NULL,
		EMPLEADO_ID bigint NOT NULL,
		CONSTRAINT USUARIO_pk PRIMARY KEY (ID)
	);

	-- foreign keys
	-- Reference: ALMACEN_ENCARGADO_ALMACEN (table: ALMACEN)
	ALTER TABLE ALMACEN
	ADD CONSTRAINT ALMACEN_ENCARGADO_ALMACEN
	FOREIGN KEY (ENCARGADO_ALMACEN_ID)
	REFERENCES ENCARGADO_ALMACEN (ID);

	-- Reference: ASIGNACION_HERRAMIENTA_FLUJO_HERRAMIENTA (table: ASIGNACION_HERRAMIENTA)
	ALTER TABLE ASIGNACION_HERRAMIENTA
	ADD CONSTRAINT ASIGNACION_HERRAMIENTA_FLUJO_HERRAMIENTA
	FOREIGN KEY (FLUJO_HERRAMIENTA_ID)
	REFERENCES FLUJO_HERRAMIENTA (ID);

	-- Reference: ASIGNACION_HERRAMIENTA_PROYECTO (table: ASIGNACION_HERRAMIENTA)
	ALTER TABLE ASIGNACION_HERRAMIENTA
	ADD CONSTRAINT ASIGNACION_HERRAMIENTA_PROYECTO
	FOREIGN KEY (PROYECTO_ID)
	REFERENCES PROYECTO (ID);

	-- Reference: ASIGNACION_MATERIAL_FLUJO_MATERIAL (table: ASIGNACION_MATERIAL)
	ALTER TABLE ASIGNACION_MATERIAL
	ADD CONSTRAINT ASIGNACION_MATERIAL_FLUJO_MATERIAL
	FOREIGN KEY (FLUJO_MATERIAL_ID)
	REFERENCES FLUJO_MATERIAL (ID);

	-- Reference: ASIGNACION_MATERIAL_PROYECTO (table: ASIGNACION_MATERIAL)
	ALTER TABLE ASIGNACION_MATERIAL
	ADD CONSTRAINT ASIGNACION_MATERIAL_PROYECTO
	FOREIGN KEY (PROYECTO_ID)
	REFERENCES PROYECTO (ID);

	-- Reference: COMPRA_MATERIAL_PROVEEDOR (table: COMPRA_MATERIAL)
	ALTER TABLE COMPRA_MATERIAL
	ADD CONSTRAINT COMPRA_MATERIAL_PROVEEDOR
	FOREIGN KEY (PROVEEDOR_ID)
	REFERENCES PROVEEDOR (ID);

	-- Reference: COMPRA_PROVEEDOR (table: COMPRA_HERRAMIENTA)
	ALTER TABLE COMPRA_HERRAMIENTA
	ADD CONSTRAINT COMPRA_PROVEEDOR
	FOREIGN KEY (PROVEEDOR_ID)
	REFERENCES PROVEEDOR (ID);

	-- Reference: DETALLE_COMPRA_HERRAMIENTA_COMPRA_HERRAMIENTA (table: DETALLE_COMPRA_HERRAMIENTA)
	ALTER TABLE DETALLE_COMPRA_HERRAMIENTA
	ADD CONSTRAINT DETALLE_COMPRA_HERRAMIENTA_COMPRA_HERRAMIENTA
	FOREIGN KEY (COMPRA_HERRAMIENTA_ID)
	REFERENCES COMPRA_HERRAMIENTA (ID);

	-- Reference: DETALLE_COMPRA_HERRAMIENTA_HERRAMIENTA (table: DETALLE_COMPRA_HERRAMIENTA)
	ALTER TABLE DETALLE_COMPRA_HERRAMIENTA
	ADD CONSTRAINT DETALLE_COMPRA_HERRAMIENTA_HERRAMIENTA
	FOREIGN KEY (HERRAMIENTA_ID)
	REFERENCES HERRAMIENTA (ID);

	-- Reference: DETALLE_COMPRA_MATERIAL_COMPRA_MATERIAL (table: DETALLE_COMPRA_MATERIAL)
	ALTER TABLE DETALLE_COMPRA_MATERIAL
	ADD CONSTRAINT DETALLE_COMPRA_MATERIAL_COMPRA_MATERIAL
	FOREIGN KEY (COMPRA_MATERIAL_ID)
	REFERENCES COMPRA_MATERIAL (ID);

	-- Reference: DETALLE_COMPRA_MATERIAL_MATERIAL (table: DETALLE_COMPRA_MATERIAL)
	ALTER TABLE DETALLE_COMPRA_MATERIAL
	ADD CONSTRAINT DETALLE_COMPRA_MATERIAL_MATERIAL
	FOREIGN KEY (MATERIAL_ID)
	REFERENCES MATERIAL (ID);

	-- Reference: EMPLEADO_EQUIPO_USUARIO (table: EMPLEADO_EQUIPO)
	ALTER TABLE EMPLEADO_EQUIPO
	ADD CONSTRAINT EMPLEADO_EQUIPO_USUARIO
	FOREIGN KEY (USUARIO_ID)
	REFERENCES USUARIO (ID);

	-- Reference: EMPLEADO_EQUIPO_EQUIPO (table: EMPLEADO_EQUIPO)
	ALTER TABLE EMPLEADO_EQUIPO
	ADD CONSTRAINT EMPLEADO_EQUIPO_EQUIPO
	FOREIGN KEY (EQUIPO_ID)
	REFERENCES EQUIPO (ID);

	-- Reference: ENCARGADO_ALMACEN_USUARIO (table: ENCARGADO_ALMACEN)
	ALTER TABLE ENCARGADO_ALMACEN
	ADD CONSTRAINT ENCARGADO_ALMACEN_USUARIO
	FOREIGN KEY (USUARIO_ID)
	REFERENCES USUARIO (ID);

	-- Reference: ENCARGADO_FINANZAS_USUARIO (table: ENCARGADO_FINANZAS)
	ALTER TABLE ENCARGADO_FINANZAS
	ADD CONSTRAINT ENCARGADO_FINANZAS_USUARIO
	FOREIGN KEY (USUARIO_ID)
	REFERENCES USUARIO (ID);

	-- Reference: ENCARGADO_PROYECTO_USUARIO (table: ENCARGADO_PROYECTO)
	ALTER TABLE ENCARGADO_PROYECTO
	ADD CONSTRAINT ENCARGADO_PROYECTO_USUARIO
	FOREIGN KEY (USUARIO_ID)
	REFERENCES USUARIO (ID);

	-- Reference: EQUIPO_PROYECTO (table: EQUIPO)
	ALTER TABLE EQUIPO
	ADD CONSTRAINT EQUIPO_PROYECTO
	FOREIGN KEY (PROYECTO_ID)
	REFERENCES PROYECTO (ID);

	-- Reference: FLUJO_HERRAMIENTA_ALMACEN (table: FLUJO_HERRAMIENTA)
	ALTER TABLE FLUJO_HERRAMIENTA
	ADD CONSTRAINT FLUJO_HERRAMIENTA_ALMACEN
	FOREIGN KEY (ALMACEN_ID)
	REFERENCES ALMACEN (ID);

	-- Reference: FLUJO_HERRAMIENTA_HERRAMIENTA (table: FLUJO_HERRAMIENTA)
	ALTER TABLE FLUJO_HERRAMIENTA
	ADD CONSTRAINT FLUJO_HERRAMIENTA_HERRAMIENTA
	FOREIGN KEY (HERRAMIENTA_ID)
	REFERENCES HERRAMIENTA (ID);

	-- Reference: GERENTE_INVENTARIO_USUARIO (table: GERENTE_INVENTARIO)
	ALTER TABLE GERENTE_INVENTARIO
	ADD CONSTRAINT GERENTE_INVENTARIO_USUARIO
	FOREIGN KEY (USUARIO_ID)
	REFERENCES USUARIO (ID);

	-- Reference: PROYECTO_ENCARGADO_FINANZAS (table: PROYECTO)
	ALTER TABLE PROYECTO
	ADD CONSTRAINT PROYECTO_ENCARGADO_FINANZAS
	FOREIGN KEY (ENCARGADO_FINANZAS_ID)
	REFERENCES ENCARGADO_FINANZAS (ID);

	-- Reference: PROYECTO_ENCARGADO_PROYECTO (table: PROYECTO)
	ALTER TABLE PROYECTO
	ADD CONSTRAINT PROYECTO_ENCARGADO_PROYECTO
	FOREIGN KEY (ENCARGADO_PROYECTO_ID)
	REFERENCES ENCARGADO_PROYECTO (ID);

	-- Reference: PROYECTO_GERENTE_INVENTARIO (table: PROYECTO)
	ALTER TABLE PROYECTO
	ADD CONSTRAINT PROYECTO_GERENTE_INVENTARIO
	FOREIGN KEY (GERENTE_INVENTARIO_ID)
	REFERENCES GERENTE_INVENTARIO (ID);

	-- Reference: REPORTE_ENCARGADO_ALMACEN (table: REPORTE)
	ALTER TABLE REPORTE
	ADD CONSTRAINT REPORTE_ENCARGADO_ALMACEN
	FOREIGN KEY (ENCARGADO_ALMACEN_ID)
	REFERENCES ENCARGADO_ALMACEN (ID);

	-- Reference: REPORTE_ENCARGADO_FINANZAS (table: REPORTE)
	ALTER TABLE REPORTE
	ADD CONSTRAINT REPORTE_ENCARGADO_FINANZAS
	FOREIGN KEY (ENCARGADO_FINANZAS_ID)
	REFERENCES ENCARGADO_FINANZAS (ID);

	-- Reference: SOBRANTE_PROYECTO_ASIGNACION_MATERIAL (table: SOBRANTE_PROYECTO)
	ALTER TABLE SOBRANTE_PROYECTO
	ADD CONSTRAINT SOBRANTE_PROYECTO_ASIGNACION_MATERIAL
	FOREIGN KEY (ASIGNACION_MATERIAL_ID)
	REFERENCES ASIGNACION_MATERIAL (ID);

	-- Reference: Table_16_ALMACEN (table: FLUJO_MATERIAL)
	ALTER TABLE FLUJO_MATERIAL
	ADD CONSTRAINT Table_16_ALMACEN
	FOREIGN KEY (ALMACEN_ID)
	REFERENCES ALMACEN (ID);

	-- Reference: Table_16_MATERIAL (table: FLUJO_MATERIAL)
	ALTER TABLE FLUJO_MATERIAL
	ADD CONSTRAINT Table_16_MATERIAL
	FOREIGN KEY (MATERIAL_ID)
	REFERENCES MATERIAL (ID);

	-- Reference: USO_MATERIAL_ASIGNACION_MATERIAL (table: USO_MATERIAL)
	ALTER TABLE USO_MATERIAL
	ADD CONSTRAINT USO_MATERIAL_ASIGNACION_MATERIAL
	FOREIGN KEY (ASIGNACION_MATERIAL_ID)
	REFERENCES ASIGNACION_MATERIAL (ID);

	-- Reference: entity_1_EMPLEADO (table: USUARIO)
	ALTER TABLE USUARIO
	ADD CONSTRAINT entity_1_EMPLEADO
	FOREIGN KEY (EMPLEADO_ID)
	REFERENCES EMPLEADO (ID);

	-- End of file.
